config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :name,presence: true
    validates :age,presence: true
    validates :party,presence: true
    validates :politics,presence: true
    has_many :votelogs
end

app/models/votelog.rb
class Votelog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
    
    before_action :find_candidate, only: [:edit, :vote, :update, :show, :destroy]

    def index   
        @candidates = Candidate.all
    end

    def edit
    end

    def vote 
        @candidate.votelogs.create(ip_address: request.remote_ip)
        redirect_to'/candidates', notice: "You have voted!"
    end

    def update
        if @candidate.update(candidate_params)
            #OK
            redirect_to'/candidates', notice: "candidate updated"
        else
            #NG
            render :edit
        end
    end
 
    def show
    end

    def destroy
        @candidate.destroy
        redirect_to'/candidates', notice: 'candidate destroyed'
    end

    def new
        @candidate = Candidate.new
    end

    def create  
        clean_params = params.require(:candidate).permit(:name, :party, :age, :politics)
        @candidate = Candidate.new(clean_params)
        if @candidate.save
            #OK
            redirect_to'/candidates', notice: "candidate created"
        else
            #NG
            render :new
        end
    end

    private
    def candidate_params
        clean_params = params.require(:candidate).permit(:name, :party, :age, :politics)
    end

    def find_candidate
        @candidate = Candidate.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>
 <ul>
    <% candidate.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>

 </ul>
<% end %>
<%= form_for(candidate) do |form|%>
<div>
<%= form.label :name %>
<%= form.text_field :name %>
</div>

<div>
<%= form.label :party %>
<%= form.text_field :party %>
</div>

<div>
<%= form.label :age %>
<%= form.text_field :age %>
</div>

<div>
<%= form.label :politics %>
<%= form.text_area :politics %>
</div>

<%= form.submit %>

<% end %>

app/views/candidates/destroy.html.erb
<h1> delete candidate</h1>

app/views/candidates/edit.html.erb
<h1> Edit candidate </h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<%= flash[:notice] %>

<h1>HI</h1>

<a href="/candidates/new">Add cadidate</a>

<table>
    <tr>
        <td></td>
        <td>votes</td>
        <td>Name</td>
        <td>Party</td>
        <td>Age</td>
        <td>Politics</td>
        <td>Action</td>
    </tr>

    <% @candidates.each do |candidate| %>
    <tr>
        <td><%= link_to 'vote', vote_candidate_path(candidate.id), method:'post'%></td>
        <td><%= candidate.votelogs_count %></td>
        <td><%= link_to candidate.name, candidate_path(candidate.id)%></td>
        <td><%= candidate.party %></td>
        <td><%= candidate.age %></td>
        <td><%= candidate.politics %></td>
        <td>
            <%= link_to 'update', edit_candidate_path(candidate.id) %>
            <%= link_to 'delete', candidate_path(candidate.id) , method: 'delete', data: {confirm: 'Are you sure?'} %>
        </td>
    </tr>
   
    <% end %>

</table>

app/views/candidates/new.html.erb
<h1>Add Candidate</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<% if @candidate %>
    <h1><%= @candidate.name %></h1>

    <ul>
        <li>party: <%= @candidate.party %></li>
        <li>age: <%= @candidate.age %></li>
        <li>politics: <%= @candidate.politics %></li>
    </ul>
<% else %>
    <h1>No record found!</h1>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>